// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
// import 'firebase_options.dart';

/// // ...
//   Firebase.initializeApp(
//    options = DefaultFirebaseOptions.currentPlatform,
//  );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqxANJlrOZirVucgiVDUs4JjsUwzEOX7Q',
    appId: '1:300827510566:web:957864362d74c4025063e7',
    messagingSenderId: '300827510566',
    projectId: 'flutterapp-782b6',
    authDomain: 'flutterapp-782b6.firebaseapp.com',
    databaseURL: 'https://flutterapp-782b6-default-rtdb.firebaseio.com',
    storageBucket: 'flutterapp-782b6.appspot.com',
    measurementId: 'G-H1VCK84Z08',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-yqG7E3jgg8lnfmvY5VolEXhE09b2OqE',
    appId: '1:300827510566:android:35961179a653239e5063e7',
    messagingSenderId: '300827510566',
    projectId: 'flutterapp-782b6',
    databaseURL: 'https://flutterapp-782b6-default-rtdb.firebaseio.com',
    storageBucket: 'flutterapp-782b6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBi35eZj4UsGed4GfdAR_xSF3cnuky4uuY',
    appId: '1:300827510566:ios:1515fdde13ed24635063e7',
    messagingSenderId: '300827510566',
    projectId: 'flutterapp-782b6',
    databaseURL: 'https://flutterapp-782b6-default-rtdb.firebaseio.com',
    storageBucket: 'flutterapp-782b6.appspot.com',
    androidClientId:
        '300827510566-1pmjbdfp2dst31dmf5vf18bcoe2aa0hk.apps.googleusercontent.com',
    iosClientId:
        '300827510566-5e3ed12qrkhsqqolhptl2rmmrmstjrpv.apps.googleusercontent.com',
    iosBundleId: 'com.example.stacklasAssignment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBi35eZj4UsGed4GfdAR_xSF3cnuky4uuY',
    appId: '1:300827510566:ios:1515fdde13ed24635063e7',
    messagingSenderId: '300827510566',
    projectId: 'flutterapp-782b6',
    databaseURL: 'https://flutterapp-782b6-default-rtdb.firebaseio.com',
    storageBucket: 'flutterapp-782b6.appspot.com',
    androidClientId:
        '300827510566-1pmjbdfp2dst31dmf5vf18bcoe2aa0hk.apps.googleusercontent.com',
    iosClientId:
        '300827510566-5e3ed12qrkhsqqolhptl2rmmrmstjrpv.apps.googleusercontent.com',
    iosBundleId: 'com.example.stacklasAssignment',
  );
}
